FROM docker:19.03.5

WORKDIR /app 

FROM python:3.7.2
RUN pip install unittest-xml-reporting
RUN pip install xmlrunner
RUN mkdir reports/results.xml
RUN chown 777 reports/results.xml
RUN
COPY test_main.py .
COPY movies.json .

CMD ["python", "./test_main.py"]
