FROM python:3.7.3

WORKDIR /app 

RUN pip install unittest-xml-reporting

RUN curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz \
  && tar xzvf docker-17.04.0-ce.tgz \
  && mv docker/docker /usr/local/bin \
  && rm -r docker docker-17.04.0-ce.tgz

COPY test_main.py .
COPY movies.json .

# CMD python test_main.py
